### ISSUE TITLE
Custom attributes

### ISSUE THREAD

**Issue by sergeysova** [openapi/actix-swagger#11]
Single attribute:

```yaml
schema:
  properties:
    demo:
      type: string
        x-rust-attribute: serde(skip_serializing_if = "Option::is_none")
```

Should generate something like:

```rust
struct Example {
  #[serde(skip_serializing_if = "Option::is_none")]
  demo: String,
}
```

---

Multiple attributes:

```yaml
schema:
  properties:
    demo:
      type: string
        x-rust-attribute:
          - serde(skip_serializing_if = “Option::is_none”)
          - validate(url)
```

Output:

```rust
struct Example {
  #[serde(skip_serializing_if = "Option::is_none")]
  #[validate(url)]
  demo: String,
}
```
