### ISSUE TITLE
Custom type

### ISSUE THREAD

**Issue by sergeysova** [openapi/actix-swagger#12]
Implemented in the printer:

https://github.com/sergeysova/actix-swagger/blob/60c65a54e829a7ca8e86463d27b7c14eecfd99f6/swagg/src/printer/components/component.rs#L169-L171

```yaml
schema:
  properties:
    demo:
      type: string
        x-rust-type: crate::app::MyType
```

Output:

```rust
struct Example {
	demo: Option<crate::app::MyType>,
}
```

---

Required:

```yaml
schema:
  required:
    - demo
  properties:
    demo:
      type: string
        x-rust-type: crate::app::MyType
```

Output:

```rust
struct Example {
	demo: crate::app::MyType,
}
```
